import {
  articleCompletionPanelDomHooks,
  articleStickyMetaDomHooks,
  articleCompletionSummaryDomHooks,
  articleShareDomHooks,
  challengePlaygroundDomHooks,
  completionDomHooks,
  directoryFilterDomHooks,
  legalPageDomHooks,
  mobileNavMenuDomHooks,
  directoryPaginationDomHooks,
  searchLauncherDomHooks,
  recentUpdatesDomHooks,
  solutionRevealDomHooks,
  trackPageDomHooks,
  trackProgressDomHooks,
} from '../../src/lib/dom-hooks'

export const e2eHookSelectors = {
  articleCompletionPanel: articleCompletionPanelDomHooks.root.selector,
  articleCompletionRelatedItem: articleCompletionSummaryDomHooks.relatedItem.selector,
  articleShareCopyButton: articleShareDomHooks.copyButton.selector,
  articleShareFeedback: articleShareDomHooks.feedback.selector,
  articleShareManualInput: articleShareDomHooks.manualInput.selector,
  articleShareReady: articleShareDomHooks.ready.selector,
  articleCompletionNextStepLink: articleCompletionSummaryDomHooks.nextStepLink.selector,
  articleCompletionNextStepTitle: articleCompletionSummaryDomHooks.nextStepTitle.selector,
  challengeAllPassingBadge: challengePlaygroundDomHooks.allPassingBadge.selector,
  challengeNoJsFallback: challengePlaygroundDomHooks.noJsFallback.selector,
  challengeRunButton: challengePlaygroundDomHooks.runButton.selector,
  challengeShareUrl: challengePlaygroundDomHooks.shareUrl.selector,
  challengeStorageWarning: challengePlaygroundDomHooks.storageWarning.selector,
  directoryFilterNoJsNote: directoryFilterDomHooks.noJsNote.selector,
  directoryItem: completionDomHooks.item.selector,
  directoryPaginationCurrentPage: `${directoryPaginationDomHooks.pageLink.selector}[aria-current="page"]`,
  directoryPaginationNextLink: directoryPaginationDomHooks.nextLink.selector,
  legalOperationalReview: legalPageDomHooks.operationalReview.selector,
  legalPublicationChecklist: legalPageDomHooks.publicationChecklist.selector,
  markUnreadButton: articleCompletionSummaryDomHooks.markUnread.selector,
  mobileNavPanel: mobileNavMenuDomHooks.panel.selector,
  mobileNavRoot: mobileNavMenuDomHooks.root.selector,
  mobileNavTrigger: mobileNavMenuDomHooks.trigger.selector,
  recentUpdatesItem: recentUpdatesDomHooks.item.selector,
  recentUpdatesRoot: recentUpdatesDomHooks.root.selector,
  searchLauncherDesktopTrigger: searchLauncherDomHooks.desktopTrigger.selector,
  searchLauncherDialog: searchLauncherDomHooks.dialog.selector,
  searchLauncherInput: searchLauncherDomHooks.input.selector,
  searchLauncherNoJsFallback: searchLauncherDomHooks.noJsFallback.selector,
  solutionRevealContent: solutionRevealDomHooks.content.selector,
  solutionRevealConfirmButton: solutionRevealDomHooks.confirmButton.selector,
  solutionRevealNoJsDetails: solutionRevealDomHooks.noJsDetails.selector,
  solutionRevealTriggerButton: solutionRevealDomHooks.triggerButton.selector,
  tocLink: articleStickyMetaDomHooks.tocLink.selector,
  trackConcept: trackPageDomHooks.concept.selector,
  trackProgressCta: trackProgressDomHooks.cta.selector,
  trackProgressNoJsNote: trackProgressDomHooks.noJsNote.selector,
  trackProgressRoot: trackProgressDomHooks.root.selector,
  trackProgressValue: trackProgressDomHooks.progressValue.selector,
} as const
